--------------------------------------------------------
-- Archivo creado  - martes-abril-11-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "VISUAL"."DEPARTAMENTO" 
   (	"DEPA_ID" NUMBER(*,0), 
	"DEPA_NOMBRE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ES
--------------------------------------------------------

  CREATE TABLE "VISUAL"."ES" 
   (	"ES_ID" NUMBER(*,0), 
	"PERS_ID" NUMBER(*,0), 
	"ES_ENTRADA" DATE, 
	"ES_SALIDA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONAS
--------------------------------------------------------

  CREATE TABLE "VISUAL"."PERSONAS" 
   (	"PERS_ID" NUMBER(*,0), 
	"DEPA_ID" NUMBER(*,0), 
	"PERS_NOMBRE" VARCHAR2(30 BYTE), 
	"PERS_PATERNO" VARCHAR2(30 BYTE), 
	"PERS_MATERNO" VARCHAR2(30 BYTE), 
	"PERS_ENTRADA" VARCHAR2(8 BYTE), 
	"PERS_SALIDA" VARCHAR2(8 BYTE), 
	"PERS_TELEFONO" VARCHAR2(10 BYTE), 
	"PERS_EMAIL" VARCHAR2(50 BYTE), 
	"PERS_ACTIVO" NUMBER(*,0), 
	"PERS_USUARIO" VARCHAR2(30 BYTE), 
	"PERS_CONTRA" VARCHAR2(30 BYTE), 
	"PERS_TIPO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE1
--------------------------------------------------------

   CREATE SEQUENCE  "VISUAL"."SEQUENCE1"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE2
--------------------------------------------------------

   CREATE SEQUENCE  "VISUAL"."SEQUENCE2"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE3
--------------------------------------------------------

   CREATE SEQUENCE  "VISUAL"."SEQUENCE3"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into VISUAL.DEPARTAMENTO
SET DEFINE OFF;
Insert into VISUAL.DEPARTAMENTO (DEPA_ID,DEPA_NOMBRE) values (1,'Ingenieria');
REM INSERTING into VISUAL.ES
SET DEFINE OFF;
Insert into VISUAL.ES (ES_ID,PERS_ID,ES_ENTRADA,ES_SALIDA) values (1,1,to_date('05/04/17','DD/MM/RR'),to_date('05/04/17','DD/MM/RR'));
Insert into VISUAL.ES (ES_ID,PERS_ID,ES_ENTRADA,ES_SALIDA) values (2,1,to_date('11/04/17','DD/MM/RR'),to_date('11/04/17','DD/MM/RR'));
Insert into VISUAL.ES (ES_ID,PERS_ID,ES_ENTRADA,ES_SALIDA) values (3,1,to_date('11/04/17','DD/MM/RR'),to_date('11/04/17','DD/MM/RR'));
Insert into VISUAL.ES (ES_ID,PERS_ID,ES_ENTRADA,ES_SALIDA) values (4,1,to_date('11/04/17','DD/MM/RR'),to_date('11/04/17','DD/MM/RR'));
REM INSERTING into VISUAL.PERSONAS
SET DEFINE OFF;
Insert into VISUAL.PERSONAS (PERS_ID,DEPA_ID,PERS_NOMBRE,PERS_PATERNO,PERS_MATERNO,PERS_ENTRADA,PERS_SALIDA,PERS_TELEFONO,PERS_EMAIL,PERS_ACTIVO,PERS_USUARIO,PERS_CONTRA,PERS_TIPO) values (1,1,'Javier','Avendaño','Jimenez','09:00:00','13:00:00','9515093153','javier@hotmail.com',1,'Javier','pass',1);
Insert into VISUAL.PERSONAS (PERS_ID,DEPA_ID,PERS_NOMBRE,PERS_PATERNO,PERS_MATERNO,PERS_ENTRADA,PERS_SALIDA,PERS_TELEFONO,PERS_EMAIL,PERS_ACTIVO,PERS_USUARIO,PERS_CONTRA,PERS_TIPO) values (2,1,'Cesar','Pichon','Pomposo','09:00:00','13:00:00','9515093153','javier@hotmail.com',1,'Cesar','pass',1);
Insert into VISUAL.PERSONAS (PERS_ID,DEPA_ID,PERS_NOMBRE,PERS_PATERNO,PERS_MATERNO,PERS_ENTRADA,PERS_SALIDA,PERS_TELEFONO,PERS_EMAIL,PERS_ACTIVO,PERS_USUARIO,PERS_CONTRA,PERS_TIPO) values (3,1,'Juan','Greñas','Locas','06:00:00','7:00:00','9511234567','asdf@eclavodejavier.com',1,'Juannitnot','pass',2);
Insert into VISUAL.PERSONAS (PERS_ID,DEPA_ID,PERS_NOMBRE,PERS_PATERNO,PERS_MATERNO,PERS_ENTRADA,PERS_SALIDA,PERS_TELEFONO,PERS_EMAIL,PERS_ACTIVO,PERS_USUARIO,PERS_CONTRA,PERS_TIPO) values (4,1,'asdsad','sadfdfgs','dsfgdg','09:00:00','13:00:00','9515093153','javier@hotmail.com',1,'Jasdvds','pass',1);
Insert into VISUAL.PERSONAS (PERS_ID,DEPA_ID,PERS_NOMBRE,PERS_PATERNO,PERS_MATERNO,PERS_ENTRADA,PERS_SALIDA,PERS_TELEFONO,PERS_EMAIL,PERS_ACTIVO,PERS_USUARIO,PERS_CONTRA,PERS_TIPO) values (5,1,'Empleado','Comun','Chafa','07:00:00','14:00:00','9511232341','hola@biencahfa.com',1,'Empleado','pass',3);
Insert into VISUAL.PERSONAS (PERS_ID,DEPA_ID,PERS_NOMBRE,PERS_PATERNO,PERS_MATERNO,PERS_ENTRADA,PERS_SALIDA,PERS_TELEFONO,PERS_EMAIL,PERS_ACTIVO,PERS_USUARIO,PERS_CONTRA,PERS_TIPO) values (6,1,'not','Al','va','null','null','987654321','@hotmail.com',1,'null','null',3);
--------------------------------------------------------
--  DDL for Index PERS_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "VISUAL"."PERS_USUARIO" ON "VISUAL"."PERSONAS" ("PERS_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_Relationship1
--------------------------------------------------------

  CREATE INDEX "VISUAL"."IX_Relationship1" ON "VISUAL"."ES" ("PERS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index Key1
--------------------------------------------------------

  CREATE UNIQUE INDEX "VISUAL"."Key1" ON "VISUAL"."PERSONAS" ("PERS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_Relationship2
--------------------------------------------------------

  CREATE INDEX "VISUAL"."IX_Relationship2" ON "VISUAL"."PERSONAS" ("DEPA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index Key3
--------------------------------------------------------

  CREATE UNIQUE INDEX "VISUAL"."Key3" ON "VISUAL"."DEPARTAMENTO" ("DEPA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index Key2
--------------------------------------------------------

  CREATE UNIQUE INDEX "VISUAL"."Key2" ON "VISUAL"."ES" ("ES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VISUAL"."TRIGGER1" 
BEFORE INSERT ON PERSONAS 
FOR EACH ROW
BEGIN
  :NEW.PERS_ID := SEQUENCE1.NEXTVAL;
END;
/
ALTER TRIGGER "VISUAL"."TRIGGER1" DISABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "VISUAL"."DEPARTAMENTO" ADD CONSTRAINT "Key3" PRIMARY KEY ("DEPA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "VISUAL"."DEPARTAMENTO" MODIFY ("DEPA_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VISUAL"."DEPARTAMENTO" MODIFY ("DEPA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "VISUAL"."PERSONAS" ADD CONSTRAINT "PERS_USUARIO" UNIQUE ("PERS_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "VISUAL"."PERSONAS" ADD CONSTRAINT "Key1" PRIMARY KEY ("PERS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "VISUAL"."PERSONAS" MODIFY ("PERS_TIPO" NOT NULL ENABLE);
  ALTER TABLE "VISUAL"."PERSONAS" MODIFY ("PERS_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "VISUAL"."PERSONAS" MODIFY ("PERS_MATERNO" NOT NULL ENABLE);
  ALTER TABLE "VISUAL"."PERSONAS" MODIFY ("PERS_PATERNO" NOT NULL ENABLE);
  ALTER TABLE "VISUAL"."PERSONAS" MODIFY ("PERS_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VISUAL"."PERSONAS" MODIFY ("PERS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ES
--------------------------------------------------------

  ALTER TABLE "VISUAL"."ES" ADD CONSTRAINT "Key2" PRIMARY KEY ("ES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "VISUAL"."ES" MODIFY ("ES_SALIDA" NOT NULL DISABLE);
  ALTER TABLE "VISUAL"."ES" MODIFY ("ES_ENTRADA" NOT NULL ENABLE);
  ALTER TABLE "VISUAL"."ES" MODIFY ("ES_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ES
--------------------------------------------------------

  ALTER TABLE "VISUAL"."ES" ADD CONSTRAINT "Relationship1" FOREIGN KEY ("PERS_ID")
	  REFERENCES "VISUAL"."PERSONAS" ("PERS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "VISUAL"."PERSONAS" ADD CONSTRAINT "Relationship2" FOREIGN KEY ("DEPA_ID")
	  REFERENCES "VISUAL"."DEPARTAMENTO" ("DEPA_ID") ENABLE;
